### ISSUE TITLE
Great work for SDL2 with Cairo - But you should replace _scale with _offset

### ISSUE THREAD

**Issue by DeafMan1983** [tsuu32/sdl2-cairo-example#1]
Hello,

I have fixed
You need replace "...scale" with "..._offset"
and 
`  cairo_surface_set_device_offset(cr_surface, cairo_x_multiplier, cairo_y_multiplier);`

It works fine.

I have ported from your source to C# But Cairo by Cra0zy or Mono Developer can't use it because byte[] was for pixels/data
I have created own CairoSharp and pixels/data uses to IntPtr now.

That is why I show you example I have made.
![image](https://user-images.githubusercontent.com/57066679/87681886-77a07580-c77f-11ea-9989-0e43cf0ac7ec.png)

Sorry for late I explain you cairo_surface_set_device_scale() is old version. That is why we would like to use with "cairo_surface_set_device_offset()" in latest libcairo.so.2 from Linux.

Best regards and stay your healthy!

**Comment by tsuu32** [comment]
Thanks for seeing my repo.
>Sorry for late I explain you cairo_surface_set_device_scale() is old version. That is why we would like to use with "cairo_surface_set_device_offset()" in latest libcairo.so.2 from Linux.

`cairo_surface_set_device_scale` is not deprecated API. See [official cairo documentation](https://www.cairographics.org/manual/cairo-cairo-surface-t.html#cairo-surface-set-device-scale).

In my environment `sdl2-cairo.c` works well. Please make sure `sdl2-cairo.c` (which is not C# ported version) works well.

**Comment by DeafMan1983** [comment]
Ok i will try.
